version: "3"
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    command: npm start
    depends_on:
      - mongodb
    volumes:
      - .:/src
      - /node_modules
    ports:
      - 80:3000
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    command: --smallfiles
    ports:
      - 27017:27017
